# Numerical Python(Numpy) - Part 1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np


In [2]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [5]:
b = np.array([1,2,3])
b*3

array([3, 6, 9])

## 1. Numpy Dimensional array

In [6]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [7]:
type(a)

numpy.ndarray

In [9]:
a.dtype, a.shape        #shape - 현재 몇차원인지 확인, dtype - 넘파이에서 타입 확인

# (dtype('float64'), (4,))          4 - 1차원

(dtype('float64'), (4,))

## 2. Array shape

In [12]:
# Vector = 1차원 표현
vec = np.array([1,4,5,8])
vec.shape

(4,)

In [15]:
# Matrix = 2차원
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [26]:
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [27]:
vec.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [29]:
# size 원소의 갯수
vec.size, matrix.size, tensor.size

(4, 6, 24)

In [36]:
# data type
# float32: 32bit로 표시 - single precision
# float64: 64bit로 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [37]:
b = np.array([1,2,3], dtype=np.int16)
b

array([1, 2, 3], dtype=int16)

## reshape

In [38]:
matrix.shape

(2, 3)

In [39]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [40]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
# size가 동일하면 reshape 가능
# -1 의 의미는 사이즈에 맞게 numpy가 알아서 조절해줌(단, 사이즈가 동일할 경우)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [45]:
matrix.reshape(3,-1).shape

(3, 2)

In [46]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
tensor.reshape(4,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])